name: CI/CD

on:
    push:
    pull_request:

jobs:
    test:
        name: Build and Test
        runs-on: ubuntu-latest
        strategy:
            fail-fast: false
            matrix:
                product: [ 'chrome', 'firefox' ]
        env:
            NODE_ENV: development

        steps:
            -   name: Checkout code
                uses: actions/checkout@v2

            -   name: Setup Node
                uses: actions/setup-node@v2
                with:
                    node-version: '16.x'
                    registry-url: 'https://registry.npmjs.org'

            -   name: Install dependencies
                run: npm ci
                env:
                    PUPPETEER_PRODUCT: ${{ matrix.product }}

            -   name: Perform tests
                run: npm test
                env:
                    PUPPETEER_PRODUCT: ${{ matrix.product }}
